# Generated by Django 3.0.6 on 2020-05-10 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Oauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('option', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='name',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='age',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='display_picture',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='location',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='skills',
        ),
        migrations.AddField(
            model_name='invoice',
            name='branding_theme_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency_rate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='invoice',
            name='expected_payment_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_amount_types',
            field=models.CharField(default='Exclusive', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='planned_payment_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='invoice',
            name='refrence',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_to_contacts',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='LineItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=4000)),
                ('quantity', models.CharField(max_length=13)),
                ('unit_amount', models.CharField(max_length=200)),
                ('item_code', models.CharField(max_length=200)),
                ('account_code', models.CharField(max_length=200)),
                ('line_item_id', models.CharField(max_length=200)),
                ('tax_type', models.CharField(max_length=200)),
                ('tax_amount', models.CharField(max_length=200)),
                ('line_amount', models.CharField(max_length=200)),
                ('discount_rate', models.CharField(max_length=200)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oauth.Tracking')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='contacts',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Oauth.Contacts'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_items',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Oauth.LineItems'),
        ),
    ]
