# Generated by Django 3.0.6 on 2020-05-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oauth', '0003_auto_20200510_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='contact_id',
            new_name='ContactID',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='branding_theme_id',
            new_name='BrandingThemeID',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='currency_code',
            new_name='CurrencyCode',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='currency_rate',
            new_name='CurrencyRate',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='due_date',
            new_name='DueDate',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='expected_payment_date',
            new_name='ExpectedPaymentDate',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_number',
            new_name='InvoiceNumber',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='planned_payment_date',
            new_name='PlannedPaymentDate',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='refrence',
            new_name='Refrence',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='sent_to_contacts',
            new_name='SentToContact',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='type',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='url',
            new_name='Url',
        ),
        migrations.RenameField(
            model_name='tracking',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='tracking',
            old_name='option',
            new_name='Option',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_amount_types',
        ),
        migrations.RemoveField(
            model_name='lineitems',
            name='account_code',
        ),
        migrations.RemoveField(
            model_name='lineitems',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lineitems',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='lineitems',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='lineitems',
            name='line_amount',
        ),
        migrations.RemoveField(
            model_name='lineitems',
            name='line_item_id',
        ),
        migrations.RemoveField(
            model_name='lineitems',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='lineitems',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='lineitems',
            name='tax_type',
        ),
        migrations.RemoveField(
            model_name='lineitems',
            name='unit_amount',
        ),
        migrations.AddField(
            model_name='contacts',
            name='Name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='LineAmountTypes',
            field=models.CharField(blank=True, default='Exclusive', max_length=100),
        ),
        migrations.AddField(
            model_name='lineitems',
            name='AccountCode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lineitems',
            name='Description',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='lineitems',
            name='DiscountRate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lineitems',
            name='ItemCode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lineitems',
            name='LineAmount',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lineitems',
            name='LineItemID',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lineitems',
            name='Quantity',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='lineitems',
            name='TaxAmount',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lineitems',
            name='TaxType',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lineitems',
            name='UnitAmount',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
