# Generated by Django 3.0.6 on 2020-05-11 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Oauth', '0005_auto_20200511_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='CurrencyCode',
            field=models.CharField(blank=True, default='INR', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='DueDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ExpectedPaymentDate',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='PlannedPaymentDate',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Type',
            field=models.CharField(default='ACCREC', max_length=100),
        ),
        migrations.AlterField(
            model_name='lineitems',
            name='TaxType',
            field=models.CharField(blank=True, default='OUTPUT', max_length=200),
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
