# Generated by Django 3.0.6 on 2020-05-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oauth', '0006_auto_20200511_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Date',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='DueDate',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ExpectedPaymentDate',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='PlannedPaymentDate',
            field=models.DateField(blank=True, default=''),
        ),
    ]
